"""
Generate EMR4 Patient File Word template (.dotx)

Creates a .dotx with:
  - Proper heading structure (patient name, DOB, Medicare)
  - Section headings for: Presenting Complaint, History, Examination,
    Assessment, Plan, Medications, Allergies
  - A Custom XML Part that tags the document as document-type="patient"
    so the taskpane SPA can detect it and switch to Patient Mode

Usage:
    .venv\\Scripts\\python create_patient_template.py
"""

import zipfile
import shutil
from pathlib import Path

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH


TEMPLATE_PATH = Path("EMR4 Patient File.dotx")
CUSTOM_XML_NS = "http://emr4.com/ns/document"

# ─────────────────────────────────────────────────────────────
# 1. Build the document content
# ─────────────────────────────────────────────────────────────

doc = Document()

# Set narrow margins
for section in doc.sections:
    section.top_margin    = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin   = Inches(1.0)
    section.right_margin  = Inches(1.0)

# --- Title block ---
title = doc.add_heading("PATIENT CLINICAL FILE", level=0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

# Patient demographics placeholder
demo = doc.add_paragraph()
demo.add_run("Patient: ").bold = True
demo.add_run("[Last Name], [First Name]")
doc.add_paragraph()

fields = [
    ("Date of Birth", "[DD/MM/YYYY]"),
    ("Medicare Number", "[XXXXXXXXX/X]"),
    ("Date of Consultation", "[DD/MM/YYYY]"),
    ("Practitioner", "[Dr Name]  ·  Provider No: [XXXXXXXX]"),
]
for label, placeholder in fields:
    p = doc.add_paragraph(style="Normal")
    run = p.add_run(f"{label}: ")
    run.bold = True
    p.add_run(placeholder)

doc.add_paragraph()  # spacer

# --- Clinical sections ---
SECTIONS = [
    ("Presenting Complaint", "Chief complaint and duration."),
    ("History of Presenting Illness", "Expand on the presenting complaint — onset, duration, severity, modifying factors."),
    ("Past Medical History", "Significant past diagnoses, surgeries, hospitalisations."),
    ("Current Medications", "Drug name · dose · frequency · route"),
    ("Allergies & Adverse Reactions", "Substance — reaction — severity"),
    ("Social & Family History", "Occupation, smoking, alcohol, recreational drugs. Family history of relevance."),
    ("Examination Findings", "Vital signs, systems examination."),
    ("Assessment / Diagnoses", "Active problem list and clinical impressions."),
    ("Management Plan", "Investigations ordered, referrals, prescriptions, safety-netting, follow-up."),
]

for heading_text, hint in SECTIONS:
    h = doc.add_heading(heading_text, level=1)
    # Style the heading colour to match EMR4 blue
    for run in h.runs:
        run.font.color.rgb = RGBColor(0, 58, 108)
    p = doc.add_paragraph(hint)
    p.runs[0].font.color.rgb = RGBColor(160, 160, 160)
    p.runs[0].italic = True
    doc.add_paragraph()

# --- Footer ---
doc.add_page_break()
footer_p = doc.add_paragraph("Generated by EMR4 Centaur · Confidential medical record")
footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
footer_p.runs[0].font.size = Pt(8)
footer_p.runs[0].font.color.rgb = RGBColor(180, 180, 180)

# ─────────────────────────────────────────────────────────────
# 2. Save as .docx first (python-docx can't write .dotx directly)
# ─────────────────────────────────────────────────────────────

TEMP_DOCX = Path("_emr4_template_tmp.docx")
doc.save(str(TEMP_DOCX))

# ─────────────────────────────────────────────────────────────
# 3. Inject Custom XML Part and convert to .dotx
# ─────────────────────────────────────────────────────────────

CUSTOM_XML_CONTENT = f"""<?xml version="1.0" encoding="UTF-8"?>
<emr4:root xmlns:emr4="{CUSTOM_XML_NS}">
  <emr4:document-type>patient</emr4:document-type>
  <emr4:version>1.0</emr4:version>
</emr4:root>"""

CUSTOM_XML_RELS_ENTRY = (
    '<Relationship Id="rIdEMR4Custom" '
    'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml" '
    'Target="../customXml/item1.xml"/>'
)

CUSTOM_XML_PROPS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ds:datastoreItem ds:itemID="{EMR4-0001-0000-0000-000000000001}"
  xmlns:ds="http://schemas.openxmlformats.org/officeDocument/2006/customXml">
  <ds:schemaRefs/>
</ds:datastoreItem>"""

DOTX_PATH = TEMPLATE_PATH

# ─────────────────────────────────────────────────────────────
# 3. Build the final .dotx in one pass — patch rels + inject XML
# ─────────────────────────────────────────────────────────────

tmp_path = Path("_emr4_patch_tmp.docx")

with zipfile.ZipFile(str(TEMP_DOCX), "r") as zf_r:
    existing_names = set(zf_r.namelist())
    rels_xml = zf_r.read("word/_rels/document.xml.rels").decode("utf-8")
    if "rIdEMR4Custom" not in rels_xml:
        rels_xml = rels_xml.replace(
            "</Relationships>",
            f"  {CUSTOM_XML_RELS_ENTRY}\n</Relationships>",
        )

    with zipfile.ZipFile(str(tmp_path), "w", zipfile.ZIP_DEFLATED) as zf_w:
        for item in zf_r.infolist():
            if item.filename == "word/_rels/document.xml.rels":
                zf_w.writestr(item, rels_xml)
            else:
                zf_w.writestr(item, zf_r.read(item.filename))

        # Inject Custom XML entries (only if not already present)
        if "customXml/item1.xml" not in existing_names:
            zf_w.writestr("customXml/item1.xml", CUSTOM_XML_CONTENT)
        if "customXml/itemProps1.xml" not in existing_names:
            zf_w.writestr("customXml/itemProps1.xml", CUSTOM_XML_PROPS)

shutil.move(str(tmp_path), str(DOTX_PATH))
TEMP_DOCX.unlink(missing_ok=True)

print(f"[OK] Template created: {DOTX_PATH.resolve()}")
print()
print("Usage:")
print("  1. Open Word -> File -> New from Existing -> select this file")
print("  2. Or double-click to open a new document based on the template")
print("  3. EMR4 Centaur will detect document-type=patient and activate Patient Mode")
