"""add_document_url_to_patients

Revision ID: 6322b34e4de4
Revises: d4787e8e3629
Create Date: 2026-06-14 22:52:36.712302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6322b34e4de4'
down_revision: Union[str, Sequence[str], None] = 'd4787e8e3629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('document_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'document_url')
    # ### end Alembic commands ###
