"""phase_0_baseline

Revision ID: d4787e8e3629
Revises: 
Create Date: 2026-06-13 22:25:59.005106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd4787e8e3629'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Truncate legacy tables so NOT NULL columns can be added cleanly (dev only)
    op.execute(
        "TRUNCATE TABLE prescriptions, mbs_claims, clinical_diagnoses, encounters, patients CASCADE"
    )
    # Pre-create enum types for add_column on existing tables (PostgreSQL requires type before column)
    op.execute("CREATE TYPE encounterstatus AS ENUM ('Draft', 'InProgress', 'Finalized', 'Amended')")
    op.execute("CREATE TYPE templatetype AS ENUM ('SOAP', 'Procedure', 'MentalHealth', 'CDM', 'GPCCMP', 'HealthAssessment', 'Antenatal', 'WoundCare')")
    op.execute("CREATE TYPE claimtype AS ENUM ('BulkBill', 'PatientClaim', 'DVA', 'WorkCover', 'TAC', 'ECLIPSE')")
    op.execute("CREATE TYPE claimstatus AS ENUM ('Draft', 'Submitted', 'Accepted', 'Rejected', 'Paid')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('address_suburb', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=10), nullable=True),
    sa.Column('address_postcode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('hive_mind_opt_in', sa.Boolean(), nullable=True),
    sa.Column('practice_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('specialty_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asgc_ra_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('proda_device_cert_path', sa.String(length=500), nullable=True),
    sa.Column('proda_cert_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('is_bookable_online', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointment_types_practice_id', 'appointment_types', ['practice_id'], unique=False)
    op.create_table('community_encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_practice_id', sa.UUID(), nullable=True),
    sa.Column('deidentified_text', sa.Text(), nullable=False),
    sa.Column('encounter_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('mbs_item', sa.String(length=20), nullable=True),
    sa.Column('snomed_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gp_tier', sa.Enum('Tier1_Gold', 'Tier2', 'Tier3', name='gptier'), nullable=True),
    sa.Column('practice_specialty_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('practice_asgc_ra_code', sa.String(length=10), nullable=True),
    sa.Column('practice_latitude', sa.Float(), nullable=True),
    sa.Column('practice_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_suburb', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=10), nullable=True),
    sa.Column('address_postcode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('waiting_rooms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practice_locations_practice_id', 'practice_locations', ['practice_id'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('substance', sa.String(length=255), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('snomed_code', sa.String(length=50), nullable=True),
    sa.Column('recorded_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allergies_patient_id', 'allergies', ['patient_id'], unique=False)
    op.create_table('ihi_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('ihi_number', sa.String(length=20), nullable=False),
    sa.Column('ihi_status', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('Manual', 'HI_Service', name='ihisource'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ihi_records_patient_id', 'ihi_records', ['patient_id'], unique=False)
    op.create_table('immunisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=255), nullable=False),
    sa.Column('dose_number', sa.String(length=10), nullable=True),
    sa.Column('date_given', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('site', sa.String(length=50), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('air_notification_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_immunisations_patient_id', 'immunisations', ['patient_id'], unique=False)
    op.create_table('patient_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('Medical', 'Surgical', 'Family', 'Social', name='historycategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_history_patient_id', 'patient_history', ['patient_id'], unique=False)
    op.create_table('patient_qr_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_patient_qr_tokens_patient_id', 'patient_qr_tokens', ['patient_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('provider_number', sa.String(length=20), nullable=True),
    sa.Column('prescriber_number', sa.String(length=20), nullable=True),
    sa.Column('ahpra_number', sa.String(length=20), nullable=True),
    sa.Column('hpi_i', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('default_location_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['default_location_id'], ['practice_locations.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practitioners_practice_id', 'practitioners', ['practice_id'], unique=False)
    op.create_table('sms_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('Outbound', 'Inbound', name='smsdirection'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('sms_type', sa.Enum('AppointmentReminder', 'Confirmation', 'ResultNotification', 'Recall', 'Bulk', 'Custom', name='smstype'), nullable=True),
    sa.Column('status', sa.Enum('Queued', 'Sent', 'Delivered', 'Failed', 'Replied', name='smsstatus'), nullable=True),
    sa.Column('clicksend_message_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sms_log_patient_id', 'sms_log', ['patient_id'], unique=False)
    op.create_index('ix_sms_log_practice_id', 'sms_log', ['practice_id'], unique=False)
    op.create_table('practitioner_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['practice_locations.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practitioner_schedules_practitioner_id', 'practitioner_schedules', ['practitioner_id'], unique=False)
    op.create_table('scanned_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('triaged_to', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('SpecialistLetter', 'Report', 'Correspondence', 'Other', name='documenttype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('triage_status', sa.Enum('Pending', 'Triaged', 'Reviewed', name='triagestatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['triaged_to'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scanned_documents_patient_id', 'scanned_documents', ['patient_id'], unique=False)
    op.create_table('schedule_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_unavailable', sa.Boolean(), nullable=True),
    sa.Column('override_start', sa.Time(), nullable=True),
    sa.Column('override_end', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_overrides_practitioner_id_date', 'schedule_overrides', ['practitioner_id', 'date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GP', 'Receptionist', 'Nurse', 'Admin', 'PracticeOwner', name='userrole'), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_practice_id', 'users', ['practice_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=True),
    sa.Column('booked_by', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Booked', 'Confirmed', 'Arrived', 'InConsult', 'Completed', 'Cancelled', 'NoShow', 'DNA', name='appointmentstatus'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('booked_via', sa.Enum('Receptionist', 'Online', 'Phone', 'Kiosk', 'App', name='bookingchannel'), nullable=True),
    sa.Column('waiting_room', sa.String(length=50), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['practice_locations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_practice_id', 'appointments', ['practice_id'], unique=False)
    op.create_index('ix_appointments_practitioner_id', 'appointments', ['practitioner_id'], unique=False)
    op.create_index('ix_appointments_start_time', 'appointments', ['start_time'], unique=False)
    op.create_table('call_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('answered_by', sa.UUID(), nullable=True),
    sa.Column('call_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.Enum('Inbound', 'Outbound', 'Telehealth', 'Missed', name='calltype'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_log_practice_id', 'call_log', ['practice_id'], unique=False)
    op.create_table('checkin_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('checkin_method', sa.Enum('Details', 'QR', 'NFC', 'FacialRecognition', name='checkinmethod'), nullable=False),
    sa.Column('checkin_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('waiting_room_assigned', sa.String(length=50), nullable=True),
    sa.Column('kiosk_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkin_events_patient_id', 'checkin_events', ['patient_id'], unique=False)
    op.create_table('internal_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('recipient_role', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('Normal', 'Urgent', 'Critical', name='messagepriority'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_internal_messages_practice_id', 'internal_messages', ['practice_id'], unique=False)
    op.create_index('ix_internal_messages_recipient_id', 'internal_messages', ['recipient_id'], unique=False)
    op.create_table('care_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('plan_type', sa.Enum('GPCCMP', 'MHTP', 'HealthAssessment45', 'HealthAssessment75', 'ATSI_HA', 'Antenatal', name='careplantype'), nullable=False),
    sa.Column('mbs_item', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Active', 'Review_Due', 'Completed', name='careplanstatus'), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_care_plans_patient_id', 'care_plans', ['patient_id'], unique=False)
    op.create_index('ix_care_plans_practice_id', 'care_plans', ['practice_id'], unique=False)
    op.create_table('clinical_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('body_site', sa.String(length=100), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_images_patient_id', 'clinical_images', ['patient_id'], unique=False)
    op.create_table('consent_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('form_type', sa.String(length=100), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_forms_patient_id', 'consent_forms', ['patient_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Issued', 'Paid', 'Overdue', 'Cancelled', name='invoicestatus'), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_patient_id', 'invoices', ['patient_id'], unique=False)
    op.create_table('mhr_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('SharedHealthSummary', 'EventSummary', 'DischargeSummary', 'Other', name='mhrdocumenttype'), nullable=False),
    sa.Column('upload_status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mhr_document_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mhr_uploads_patient_id', 'mhr_uploads', ['patient_id'], unique=False)
    op.create_table('rag_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('retrieved_community_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_feedback_practice_id', 'rag_feedback', ['practice_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('referral_to', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Sent', 'Accepted', 'Completed', name='referralstatus'), nullable=True),
    sa.Column('letter_document_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_referrals_patient_id', 'referrals', ['patient_id'], unique=False)
    op.create_table('test_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=True),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.Enum('Pathology', 'Radiology', 'Specialist', 'Other', name='requesttype'), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'ResultReceived', 'Reviewed', name='requeststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_requests_patient_id', 'test_requests', ['patient_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('test_request_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('result_source', sa.Enum('PIT', 'HL7', 'Manual', 'Scan', name='resultsource'), nullable=False),
    sa.Column('lab_name', sa.String(length=255), nullable=True),
    sa.Column('specimen_date', sa.Date(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('New', 'Reviewed', 'ActionRequired', 'Filed', name='resultstatus'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('display_pdf_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['test_request_id'], ['test_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_results_patient_id', 'results', ['patient_id'], unique=False)
    op.create_index('ix_results_practice_id', 'results', ['practice_id'], unique=False)
    op.create_index('ix_results_status', 'results', ['status'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by_result_id', sa.UUID(), nullable=True),
    sa.Column('reminder_type', sa.Enum('ResultFollowUp', 'Recall', 'ReviewAppointment', 'CarePlanReview', 'Custom', name='remindertype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_patient_id', 'reminders', ['patient_id'], unique=False)
    op.create_index('ix_reminders_practice_id', 'reminders', ['practice_id'], unique=False)
    op.create_table('result_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('flag', sa.Enum('Normal', 'Low', 'High', 'Critical', name='resultflag'), nullable=True),
    sa.Column('loinc_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_result_items_result_id', 'result_items', ['result_id'], unique=False)
    op.add_column('clinical_diagnoses', sa.Column('practice_id', sa.UUID(), nullable=False))
    op.add_column('clinical_diagnoses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('clinical_diagnoses', sa.Column('onset_date', sa.Date(), nullable=True))
    op.add_column('clinical_diagnoses', sa.Column('resolved_date', sa.Date(), nullable=True))
    op.add_column('clinical_diagnoses', sa.Column('severity', sa.String(length=50), nullable=True))
    op.alter_column('clinical_diagnoses', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_clinical_diagnoses_patient_id', 'clinical_diagnoses', ['patient_id'], unique=False)
    op.create_index('ix_clinical_diagnoses_practice_id', 'clinical_diagnoses', ['practice_id'], unique=False)
    op.create_foreign_key(None, 'clinical_diagnoses', 'practices', ['practice_id'], ['id'])
    op.add_column('encounters', sa.Column('practice_id', sa.UUID(), nullable=False))
    op.add_column('encounters', sa.Column('practitioner_id', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('appointment_id', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('status', sa.Enum('Draft', 'InProgress', 'Finalized', 'Amended', name='encounterstatus'), nullable=True))
    op.add_column('encounters', sa.Column('template_type', sa.Enum('SOAP', 'Procedure', 'MentalHealth', 'CDM', 'GPCCMP', 'HealthAssessment', 'Antenatal', 'WoundCare', name='templatetype'), nullable=True))
    op.add_column('encounters', sa.Column('is_shared_to_hive', sa.Boolean(), nullable=True))
    op.add_column('encounters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('encounters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('encounters', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('encounters', 'google_doc_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_encounters_patient_id', 'encounters', ['patient_id'], unique=False)
    op.create_index('ix_encounters_practice_id', 'encounters', ['practice_id'], unique=False)
    op.create_foreign_key(None, 'encounters', 'practices', ['practice_id'], ['id'])
    op.create_foreign_key(None, 'encounters', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(None, 'encounters', 'practitioners', ['practitioner_id'], ['id'])
    op.add_column('mbs_claims', sa.Column('practice_id', sa.UUID(), nullable=False))
    op.add_column('mbs_claims', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.add_column('mbs_claims', sa.Column('practitioner_id', sa.UUID(), nullable=True))
    op.add_column('mbs_claims', sa.Column('claim_type', sa.Enum('BulkBill', 'PatientClaim', 'DVA', 'WorkCover', 'TAC', 'ECLIPSE', name='claimtype'), nullable=True))
    op.add_column('mbs_claims', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('mbs_claims', sa.Column('gateway_claim_id', sa.String(length=100), nullable=True))
    op.add_column('mbs_claims', sa.Column('claim_status', sa.Enum('Draft', 'Submitted', 'Accepted', 'Rejected', 'Paid', name='claimstatus'), nullable=True))
    op.add_column('mbs_claims', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mbs_claims', sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_mbs_claims_claim_status', 'mbs_claims', ['claim_status'], unique=False)
    op.create_index('ix_mbs_claims_patient_id', 'mbs_claims', ['patient_id'], unique=False)
    op.create_index('ix_mbs_claims_practice_id', 'mbs_claims', ['practice_id'], unique=False)
    op.create_foreign_key(None, 'mbs_claims', 'practices', ['practice_id'], ['id'])
    op.create_foreign_key(None, 'mbs_claims', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'mbs_claims', 'practitioners', ['practitioner_id'], ['id'])
    op.drop_column('mbs_claims', 'status')
    op.add_column('patients', sa.Column('practice_id', sa.UUID(), nullable=False))
    op.add_column('patients', sa.Column('dva_number', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('gender_identity', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('indigenous_status', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('preferred_language', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('phone_mobile', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('phone_home', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('address_suburb', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('address_state', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('address_postcode', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_name', sa.String(length=200), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('concession_type', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('consent_facial_recognition', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('face_embedding_id', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('sms_consent', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('sms_consent_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index('ix_patients_last_name', 'patients', ['last_name'], unique=False)
    op.create_index('ix_patients_medicare_number', 'patients', ['medicare_number'], unique=False)
    op.create_index('ix_patients_practice_id', 'patients', ['practice_id'], unique=False)
    op.create_foreign_key(None, 'patients', 'practices', ['practice_id'], ['id'])
    op.add_column('prescriptions', sa.Column('practice_id', sa.UUID(), nullable=False))
    op.add_column('prescriptions', sa.Column('prescribed_by', sa.UUID(), nullable=True))
    op.add_column('prescriptions', sa.Column('pbs_code', sa.String(length=20), nullable=True))
    op.add_column('prescriptions', sa.Column('repeats', sa.String(length=10), nullable=True))
    op.add_column('prescriptions', sa.Column('quantity', sa.String(length=20), nullable=True))
    op.add_column('prescriptions', sa.Column('route', sa.String(length=50), nullable=True))
    op.add_column('prescriptions', sa.Column('frequency', sa.String(length=100), nullable=True))
    op.add_column('prescriptions', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('prescriptions', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('prescriptions', sa.Column('erx_token', sa.String(length=255), nullable=True))
    op.add_column('prescriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_prescriptions_patient_id', 'prescriptions', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'prescriptions', 'practitioners', ['prescribed_by'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'practices', ['practice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_index('ix_prescriptions_patient_id', table_name='prescriptions')
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('prescriptions', 'created_at')
    op.drop_column('prescriptions', 'erx_token')
    op.drop_column('prescriptions', 'end_date')
    op.drop_column('prescriptions', 'start_date')
    op.drop_column('prescriptions', 'frequency')
    op.drop_column('prescriptions', 'route')
    op.drop_column('prescriptions', 'quantity')
    op.drop_column('prescriptions', 'repeats')
    op.drop_column('prescriptions', 'pbs_code')
    op.drop_column('prescriptions', 'prescribed_by')
    op.drop_column('prescriptions', 'practice_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index('ix_patients_practice_id', table_name='patients')
    op.drop_index('ix_patients_medicare_number', table_name='patients')
    op.drop_index('ix_patients_last_name', table_name='patients')
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'sms_consent_date')
    op.drop_column('patients', 'sms_consent')
    op.drop_column('patients', 'face_embedding_id')
    op.drop_column('patients', 'consent_facial_recognition')
    op.drop_column('patients', 'concession_type')
    op.drop_column('patients', 'emergency_contact_relationship')
    op.drop_column('patients', 'emergency_contact_phone')
    op.drop_column('patients', 'emergency_contact_name')
    op.drop_column('patients', 'address_postcode')
    op.drop_column('patients', 'address_state')
    op.drop_column('patients', 'address_suburb')
    op.drop_column('patients', 'address_line1')
    op.drop_column('patients', 'phone_home')
    op.drop_column('patients', 'phone_mobile')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'preferred_language')
    op.drop_column('patients', 'indigenous_status')
    op.drop_column('patients', 'gender_identity')
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'dva_number')
    op.drop_column('patients', 'practice_id')
    op.add_column('mbs_claims', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mbs_claims', type_='foreignkey')
    op.drop_constraint(None, 'mbs_claims', type_='foreignkey')
    op.drop_constraint(None, 'mbs_claims', type_='foreignkey')
    op.drop_index('ix_mbs_claims_practice_id', table_name='mbs_claims')
    op.drop_index('ix_mbs_claims_patient_id', table_name='mbs_claims')
    op.drop_index('ix_mbs_claims_claim_status', table_name='mbs_claims')
    op.drop_column('mbs_claims', 'response_data')
    op.drop_column('mbs_claims', 'submitted_at')
    op.drop_column('mbs_claims', 'claim_status')
    op.drop_column('mbs_claims', 'gateway_claim_id')
    op.drop_column('mbs_claims', 'amount')
    op.drop_column('mbs_claims', 'claim_type')
    op.drop_column('mbs_claims', 'practitioner_id')
    op.drop_column('mbs_claims', 'patient_id')
    op.drop_column('mbs_claims', 'practice_id')
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_index('ix_encounters_practice_id', table_name='encounters')
    op.drop_index('ix_encounters_patient_id', table_name='encounters')
    op.alter_column('encounters', 'google_doc_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('encounters', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('encounters', 'updated_at')
    op.drop_column('encounters', 'created_at')
    op.drop_column('encounters', 'is_shared_to_hive')
    op.drop_column('encounters', 'template_type')
    op.drop_column('encounters', 'status')
    op.drop_column('encounters', 'appointment_id')
    op.drop_column('encounters', 'practitioner_id')
    op.drop_column('encounters', 'practice_id')
    op.drop_constraint(None, 'clinical_diagnoses', type_='foreignkey')
    op.drop_index('ix_clinical_diagnoses_practice_id', table_name='clinical_diagnoses')
    op.drop_index('ix_clinical_diagnoses_patient_id', table_name='clinical_diagnoses')
    op.alter_column('clinical_diagnoses', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('clinical_diagnoses', 'severity')
    op.drop_column('clinical_diagnoses', 'resolved_date')
    op.drop_column('clinical_diagnoses', 'onset_date')
    op.drop_column('clinical_diagnoses', 'is_active')
    op.drop_column('clinical_diagnoses', 'practice_id')
    op.drop_index('ix_result_items_result_id', table_name='result_items')
    op.drop_table('result_items')
    op.drop_index('ix_reminders_practice_id', table_name='reminders')
    op.drop_index('ix_reminders_patient_id', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_results_status', table_name='results')
    op.drop_index('ix_results_practice_id', table_name='results')
    op.drop_index('ix_results_patient_id', table_name='results')
    op.drop_table('results')
    op.drop_index('ix_test_requests_patient_id', table_name='test_requests')
    op.drop_table('test_requests')
    op.drop_index('ix_referrals_patient_id', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('ix_rag_feedback_practice_id', table_name='rag_feedback')
    op.drop_table('rag_feedback')
    op.drop_index('ix_mhr_uploads_patient_id', table_name='mhr_uploads')
    op.drop_table('mhr_uploads')
    op.drop_index('ix_invoices_patient_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_consent_forms_patient_id', table_name='consent_forms')
    op.drop_table('consent_forms')
    op.drop_index('ix_clinical_images_patient_id', table_name='clinical_images')
    op.drop_table('clinical_images')
    op.drop_index('ix_care_plans_practice_id', table_name='care_plans')
    op.drop_index('ix_care_plans_patient_id', table_name='care_plans')
    op.drop_table('care_plans')
    op.drop_index('ix_internal_messages_recipient_id', table_name='internal_messages')
    op.drop_index('ix_internal_messages_practice_id', table_name='internal_messages')
    op.drop_table('internal_messages')
    op.drop_index('ix_checkin_events_patient_id', table_name='checkin_events')
    op.drop_table('checkin_events')
    op.drop_index('ix_call_log_practice_id', table_name='call_log')
    op.drop_table('call_log')
    op.drop_index('ix_appointments_start_time', table_name='appointments')
    op.drop_index('ix_appointments_practitioner_id', table_name='appointments')
    op.drop_index('ix_appointments_practice_id', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_users_practice_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_schedule_overrides_practitioner_id_date', table_name='schedule_overrides')
    op.drop_table('schedule_overrides')
    op.drop_index('ix_scanned_documents_patient_id', table_name='scanned_documents')
    op.drop_table('scanned_documents')
    op.drop_index('ix_practitioner_schedules_practitioner_id', table_name='practitioner_schedules')
    op.drop_table('practitioner_schedules')
    op.drop_index('ix_sms_log_practice_id', table_name='sms_log')
    op.drop_index('ix_sms_log_patient_id', table_name='sms_log')
    op.drop_table('sms_log')
    op.drop_index('ix_practitioners_practice_id', table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index('ix_patient_qr_tokens_patient_id', table_name='patient_qr_tokens')
    op.drop_table('patient_qr_tokens')
    op.drop_index('ix_patient_history_patient_id', table_name='patient_history')
    op.drop_table('patient_history')
    op.drop_index('ix_immunisations_patient_id', table_name='immunisations')
    op.drop_table('immunisations')
    op.drop_index('ix_ihi_records_patient_id', table_name='ihi_records')
    op.drop_table('ihi_records')
    op.drop_index('ix_allergies_patient_id', table_name='allergies')
    op.drop_table('allergies')
    op.drop_index('ix_practice_locations_practice_id', table_name='practice_locations')
    op.drop_table('practice_locations')
    op.drop_table('community_encounters')
    op.drop_index('ix_appointment_types_practice_id', table_name='appointment_types')
    op.drop_table('appointment_types')
    op.drop_table('practices')
    # ### end Alembic commands ###
