"""LC2 Corpus Factory — provenance tiers, promotion, quarantine, registry, wrapper.

This module is a strict pure-Python/Pydantic domain layer for the LC2 corpus
factory. It defines the provenance model, promotion rules, quarantine logic,
candidate registry, and the CorpusCandidate wrapper that embeds an unchanged
ReceptionScenarioSpec.

No provider, route, database, HTTP, or external-service dependency is
imported.  The module validates shape and policy only — it does not
semantically certify any candidate.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing_extensions import assert_never

# ─── LC1 canonical import (read-only reference) ────────────────────────────
from app.services.bernie.scenario_spec import ReceptionScenarioSpec

# ═══════════════════════════════════════════════════════════════════════════
#  Core enumerations
# ═══════════════════════════════════════════════════════════════════════════


class ProvenanceTier(str, Enum):
    """Provenance tier for a corpus candidate.

    - **gold**: Human/Sol-authored or independently adjudicated reference.
      Never generated by a model.
    - **silver**: Model-generated from a Gold seed, awaiting independent
      adjudication.
    - **bronze**: Unstructured or externally-sourced material that requires
      semantic adjudication before promotion.
    """

    GOLD = "gold"
    SILVER = "silver"
    BRONZE = "bronze"


class AdjudicationState(str, Enum):
    """Adjudication state of a corpus candidate.

    Only Sol (the protected orchestrator/integrator) may change a candidate's
    adjudication from ``pending`` to ``adjudicated``.
    """

    ADJUDICATED = "adjudicated"
    PENDING = "pending"
    QUARANTINE = "quarantine"


class ScenarioFamily(str, Enum):
    """Known scenario families in the LC1/LCCorpus."""

    BOOKING_CREATE = "booking_create"
    CLARIFY_TEMPORAL = "clarify_temporal"
    # Additional families may be added as the corpus grows.


class QuarantineReason(str, Enum):
    """Machine-readable reasons for quarantining a candidate.

    Every quarantine outcome must carry exactly one of these reasons.
    """

    SELF_CERTIFICATION = "self_certification"
    SCHEMA_INVALID = "schema_invalid"
    AUTHORITY_BREACH = "authority_breach"
    EVIDENCE_MISMATCH = "evidence_mismatch"
    MISSING_PROVENANCE = "missing_provenance"
    UNSAFE_INSTRUCTION = "unsafe_instruction"
    INVALID_TIER_TRANSITION = "invalid_tier_transition"
    GENERATOR_EQUALS_JUDGE = "generator_equals_judge"
    MISSING_SOURCE_GOLD = "missing_source_gold"


# ═══════════════════════════════════════════════════════════════════════════
#  Generator / Judge identity records
# ═══════════════════════════════════════════════════════════════════════════


class GeneratorIdentity(BaseModel):
    """Immutable identity record for a candidate generator.

    Stable identity comparison is by (model_id, instance_id) — two records
    with the same model and instance are considered the same generator.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    model_id: str = Field(min_length=1, description="Generator model identifier")
    instance_id: str | None = Field(
        default=None,
        description="Optional instance or lane identifier for disambiguation",
    )

    def stable_key(self) -> str:
        """Return a deterministic string key for identity comparison."""
        return f"{self.model_id}::{self.instance_id or ''}"


class JudgeIdentity(BaseModel):
    """Immutable identity record for an independent judge.

    Stable identity comparison is by (model_id, instance_id), identical in
    structure to GeneratorIdentity.  The factory rejects any promotion where
    ``generator.stable_key() == judge.stable_key()``.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    model_id: str = Field(min_length=1, description="Judge model identifier")
    instance_id: str | None = Field(
        default=None,
        description="Optional instance or lane identifier for disambiguation",
    )

    def stable_key(self) -> str:
        return f"{self.model_id}::{self.instance_id or ''}"


# ═══════════════════════════════════════════════════════════════════════════
#  Promotion-history record
# ═══════════════════════════════════════════════════════════════════════════


class PromotionEvent(BaseModel):
    """One recorded promotion step in a candidate's history."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    from_tier: ProvenanceTier
    to_tier: ProvenanceTier
    timestamp: datetime
    judge: JudgeIdentity | None = None
    reason: str | None = None


# ═══════════════════════════════════════════════════════════════════════════
#  Quarantine detail (carried inside PromotionResult for rejected cases)
# ═══════════════════════════════════════════════════════════════════════════


class QuarantineDetail(BaseModel):
    """Detail record attached to a quarantine promotion result."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    reason: QuarantineReason
    message: str = Field(min_length=1)
    details: dict[str, Any] | None = None


# ═══════════════════════════════════════════════════════════════════════════
#  Promotion result (discriminated union via tagged union pattern)
# ═══════════════════════════════════════════════════════════════════════════


class PromotionOutcome:
    """Namespace for promotion-result types so callers can pattern-match.

    Usage::

        result = promote_candidate(candidate, judge)
        if isinstance(result, PromotionOutcome.Promoted):
            ...
        elif isinstance(result, PromotionOutcome.Quarantined):
            ...
        elif isinstance(result, PromotionOutcome.Rejected):
            ...
    """

    class Promoted(BaseModel):
        """The candidate was successfully promoted."""

        model_config = ConfigDict(extra="forbid", frozen=True)

        outcome: Literal["promoted"] = "promoted"
        new_tier: ProvenanceTier
        new_adjudication: AdjudicationState
        event: PromotionEvent

    class Quarantined(BaseModel):
        """The candidate was placed in quarantine with a reason."""

        model_config = ConfigDict(extra="forbid", frozen=True)

        outcome: Literal["quarantined"] = "quarantined"
        quarantine: QuarantineDetail

    class Rejected(BaseModel):
        """The candidate was rejected (not eligible for the requested promotion)."""

        model_config = ConfigDict(extra="forbid", frozen=True)

        outcome: Literal["rejected"] = "rejected"
        reason: str = Field(min_length=1)


PromotionResult = (
    PromotionOutcome.Promoted
    | PromotionOutcome.Quarantined
    | PromotionOutcome.Rejected
)


# ═══════════════════════════════════════════════════════════════════════════
#  CorpusCandidate wrapper
# ═══════════════════════════════════════════════════════════════════════════


def _compute_derivation_id(
    source_scenario_id: str,
    generator_key: str,
    generation_timestamp: datetime,
    *,
    seed: str = "",
) -> str:
    """Deterministic derivation ID from source, generator, and timestamp."""
    raw = f"{source_scenario_id}::{generator_key}::{generation_timestamp.isoformat()}::{seed}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:32]


class CorpusCandidate(BaseModel):
    """Strict evidence wrapper around a ``ReceptionScenarioSpec``.

    This type is the unit of transport between workers.  The embedded scenario
    spec is never mutated by the wrapper; all provenance metadata lives in
    wrapper fields.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    # ── Mandatory provenance fields ───────────────────────────────────────
    provenance: ProvenanceTier
    adjudication: AdjudicationState
    family: ScenarioFamily

    generator_identity: GeneratorIdentity | None = None
    judge_identity: JudgeIdentity | None = None
    generation_timestamp: datetime | None = None

    # Source Gold scenario ID (required for Silver/Bronze; may be None for Gold)
    source_scenario_id: str | None = Field(
        default=None, min_length=1, description="Source Gold scenario_id"
    )

    # Stable derivation identifier — reproducible from source + params
    derivation_id: str | None = Field(
        default=None, min_length=1, description="SHA-256-based derivation hash"
    )
    derivation_seed: str = Field(
        default="", description="Seed string fed into derivation hash"
    )

    # Promotion history (oldest first)
    promotion_history: list[PromotionEvent] = Field(default_factory=list)

    # ── Embedded LC1 scenario (never mutated by this wrapper) ─────────────
    scenario: ReceptionScenarioSpec

    # ── Validators ────────────────────────────────────────────────────────

    @field_validator("generation_timestamp", mode="before")
    @classmethod
    def _coerce_timestamp(cls, value: object) -> object:
        if isinstance(value, str):
            return datetime.fromisoformat(value)
        return value

    @model_validator(mode="after")
    def _validate_provenance_consistency(self) -> "CorpusCandidate":
        """Fail-closed checks for missing/mismatched provenance."""
        # Gold requires no generator identity (never model-generated)
        if self.provenance == ProvenanceTier.GOLD:
            if self.generator_identity is not None:
                raise ValueError("Gold candidates must not carry a generator_identity")
            if self.adjudication != AdjudicationState.ADJUDICATED:
                raise ValueError("Gold candidates must be adjudicated")
            if self.source_scenario_id is not None:
                raise ValueError("Gold candidates must not carry a source_scenario_id")
        elif self.provenance in (ProvenanceTier.SILVER, ProvenanceTier.BRONZE):
            if self.generator_identity is None:
                raise ValueError(
                    f"{self.provenance.value} candidates must carry a generator_identity"
                )
            if self.generation_timestamp is None:
                raise ValueError(
                    f"{self.provenance.value} candidates must carry a generation_timestamp"
                )
            if self.source_scenario_id is None:
                raise ValueError(
                    f"{self.provenance.value} candidates must carry a source_scenario_id"
                )

        # Gold candidates must have source_scenario_id unset
        # (they are the source, not derived from one)
        return self

    @model_validator(mode="after")
    def _validate_derivation_id(self) -> "CorpusCandidate":
        """Auto-compute derivation_id if not provided."""
        if self.derivation_id is None and self.provenance in (
            ProvenanceTier.SILVER,
            ProvenanceTier.BRONZE,
        ):
            gen_key = (
                self.generator_identity.stable_key()
                if self.generator_identity
                else "unknown"
            )
            ts = self.generation_timestamp or datetime.now(timezone.utc)
            src = self.source_scenario_id or "unknown"
            object.__setattr__(
                self,
                "derivation_id",
                _compute_derivation_id(
                    src, gen_key, ts, seed=self.derivation_seed
                ),
            )
        return self

    def stable_key(self) -> str:
        """Return a deterministic key for identity/equality comparison."""
        return f"{self.provenance.value}::{self.scenario.scenario_id}::{self.derivation_id or ''}"

    def derive(self, **overrides: Any) -> "CorpusCandidate":
        """Produce a derived candidate with overridden fields.

        This is a convenience for generators that need to create a new
        candidate from an existing one with modified fields.  The embedded
        scenario is shallow-copied (objects reused, not deep-cloned).
        """
        data = self.model_dump(exclude={"scenario"})
        data.update(overrides)
        return CorpusCandidate(scenario=self.scenario, **data)


# ═══════════════════════════════════════════════════════════════════════════
#  Promotion engine
# ═══════════════════════════════════════════════════════════════════════════


def _check_self_certification(
    candidate: CorpusCandidate, judge: JudgeIdentity | None
) -> QuarantineDetail | None:
    """Return a quarantine detail if the candidate is self-certified."""
    if candidate.generator_identity is None:
        return None
    if judge is None:
        return None
    if candidate.generator_identity.stable_key() == judge.stable_key():
        return QuarantineDetail(
            reason=QuarantineReason.SELF_CERTIFICATION,
            message="Generator and judge identities must differ",
            details={
                "generator": candidate.generator_identity.stable_key(),
                "judge": judge.stable_key(),
            },
        )
    return None


def _check_schema_validity(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if the embedded scenario fails validation."""
    try:
        # Re-validate the embedded scenario by constructing a fresh instance
        _ = ReceptionScenarioSpec.model_validate(
            candidate.scenario.model_dump()
        )
    except Exception as exc:
        return QuarantineDetail(
            reason=QuarantineReason.SCHEMA_INVALID,
            message=f"Embedded scenario validation failed: {exc}",
        )
    return None


def _check_authority_boundary(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if the candidate claims prohibited authority.

    No generated Silver/Bronze candidate may claim provider, write, or
    confirmation authority.  Currently the authority boundary is enforced by
    the scenario schema itself (which has no such fields), so this is a
    structural check.
    """
    # The ReceptionScenarioSpec schema is inherently authority-free — it
    # contains no provider, write, or confirmation fields.  We verify the
    # candidate does not attempt to embed non-null values in fields that
    # would imply authority.
    scenario = candidate.scenario
    # Check that no forbidden values leak through expected fields
    forbidden_patterns = {
        "provider",
        "write_authority",
        "confirmation",
        "provider_call",
    }
    dump = scenario.model_dump()
    for key, value in dump.items():
        if isinstance(value, str):
            lower = value.lower()
            for pattern in forbidden_patterns:
                if pattern in lower:
                    return QuarantineDetail(
                        reason=QuarantineReason.AUTHORITY_BREACH,
                        message=f"Field '{key}' contains authority-related content: '{value}'",
                        details={"field": key, "value": value, "pattern": pattern},
                    )
    return None


def _check_evidence_mismatch(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if source spans don't match utterance text."""
    scenario = candidate.scenario
    utterances = [
        turn.get("utterance", "")
        for turn in scenario.dialogue_turns
        if isinstance(turn, dict) and "utterance" in turn
    ]
    for field_name, spans in scenario.source_spans.items():
        for span in spans:
            # Support both dict (from model_construct) and ScenarioSourceSpan
            if isinstance(span, dict):
                turn_index = span.get("turn_index", 0)
                start = span.get("start", 0)
                end = span.get("end", 0)
                text = span.get("text", "")
            else:
                turn_index = span.turn_index
                start = span.start
                end = span.end
                text = span.text
            if turn_index >= len(utterances):
                return QuarantineDetail(
                    reason=QuarantineReason.EVIDENCE_MISMATCH,
                    message=f"source_spans[{field_name!r}] references missing turn {turn_index}",
                    details={
                        "field": field_name,
                        "turn_index": turn_index,
                        "available_turns": len(utterances),
                    },
                )
            original = utterances[turn_index]
            if end > len(original) or original[start:end] != text:
                return QuarantineDetail(
                    reason=QuarantineReason.EVIDENCE_MISMATCH,
                    message=(
                        f"source_spans[{field_name!r}] text mismatch at "
                        f"turn {turn_index}[{start}:{end}]: "
                        f"expected {original[start:end]!r}, got {text!r}"
                    ),
                    details={
                        "field": field_name,
                        "turn_index": turn_index,
                        "start": start,
                        "end": end,
                        "expected": original[start:end],
                        "got": text,
                    },
                )
    return None


def _check_missing_provenance(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if required provenance fields are missing."""
    # The Pydantic model already enforces presence via field validators.
    # This is a belt-and-suspenders check.
    if candidate.provenance in (ProvenanceTier.SILVER, ProvenanceTier.BRONZE):
        missing = []
        if candidate.generator_identity is None:
            missing.append("generator_identity")
        if candidate.generation_timestamp is None:
            missing.append("generation_timestamp")
        if candidate.source_scenario_id is None:
            missing.append("source_scenario_id")
        if missing:
            return QuarantineDetail(
                reason=QuarantineReason.MISSING_PROVENANCE,
                message=f"Missing required provenance fields: {', '.join(missing)}",
                details={"missing_fields": missing},
            )
    return None


def promote_candidate(
    candidate: CorpusCandidate,
    judge: JudgeIdentity | None = None,
    *,
    target_tier: ProvenanceTier | None = None,
) -> PromotionResult:
    """Attempt to promote a candidate to the next tier.

    This function is the sole deterministic promotion gate.  It checks:

    * Self-certification (generator == judge)
    * Schema validity of the embedded scenario
    * Authority-boundary compliance
    * Source-span evidence match
    * Missing provenance fields
    * Valid tier transitions

    Parameters
    ----------
    candidate :
        The corpus candidate to promote.
    judge :
        The identity of the independent judge.  Must differ from the
        candidate's generator identity for any promotion beyond Bronze.
    target_tier :
        Explicit target tier for the promotion.  If omitted, the default
        transition path is used (Bronze -> Silver, Silver -> Gold).

    Returns
    -------
    PromotionResult
        ``Promoted`` if the promotion succeeds, ``Quarantined`` or
        ``Rejected`` otherwise.
    """
    # ── Belt-and-suspenders: re-check Pydantic validity ──────────────────
    # (Pydantic frozen models are validated at construction time, so this
    #  catches mis-constructed candidates early.)
    try:
        _ = candidate.model_dump()
    except Exception as exc:
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.SCHEMA_INVALID,
                message=f"Candidate model validation failed: {exc}",
            )
        )

    # ── Run all quarantine checks ─────────────────────────────────────────
    checks = [
        ("self-certification", _check_self_certification(candidate, judge)),
        ("schema validity", _check_schema_validity(candidate)),
        ("authority boundary", _check_authority_boundary(candidate)),
        ("evidence match", _check_evidence_mismatch(candidate)),
        ("missing provenance", _check_missing_provenance(candidate)),
    ]

    for check_name, detail in checks:
        if detail is not None:
            return PromotionOutcome.Quarantined(quarantine=detail)

    # ── Determine target tier ─────────────────────────────────────────────
    current_tier = candidate.provenance

    if target_tier is None:
        if current_tier == ProvenanceTier.BRONZE:
            target_tier = ProvenanceTier.SILVER
        elif current_tier == ProvenanceTier.SILVER:
            target_tier = ProvenanceTier.GOLD
        elif current_tier == ProvenanceTier.GOLD:
            return PromotionOutcome.Rejected(
                reason="Gold candidates cannot be promoted further"
            )
        else:
            return PromotionOutcome.Rejected(
                reason=f"Unknown provenance tier: {current_tier}"
            )

    # ── Validate transition legality ──────────────────────────────────────
    valid_transitions = {
        ProvenanceTier.BRONZE: {ProvenanceTier.SILVER},
        ProvenanceTier.SILVER: {ProvenanceTier.GOLD},
        ProvenanceTier.GOLD: set(),
    }

    allowed = valid_transitions.get(current_tier, set())
    if target_tier not in allowed:
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.INVALID_TIER_TRANSITION,
                message=(
                    f"Invalid transition: {current_tier.value} -> "
                    f"{target_tier.value}"
                ),
                details={
                    "from": current_tier.value,
                    "to": target_tier.value,
                    "allowed": [t.value for t in allowed],
                },
            )
        )

    # ── Promotion-specific checks ─────────────────────────────────────────
    if target_tier == ProvenanceTier.GOLD:
        # Only Silver candidates can be promoted to Gold
        if current_tier != ProvenanceTier.SILVER:
            return PromotionOutcome.Quarantined(
                quarantine=QuarantineDetail(
                    reason=QuarantineReason.INVALID_TIER_TRANSITION,
                    message=f"Only Silver candidates may be promoted to Gold",
                )
            )
        # Gold promotion requires an independent judge
        if judge is None:
            return PromotionOutcome.Quarantined(
                quarantine=QuarantineDetail(
                    reason=QuarantineReason.MISSING_PROVENANCE,
                    message="Gold promotion requires an independent judge",
                )
            )
        # Generator != Judge already checked above

    # ── Compute promotion event ───────────────────────────────────────────
    new_adjudication = (
        AdjudicationState.ADJUDICATED
        if target_tier == ProvenanceTier.GOLD
        else AdjudicationState.PENDING
    )

    event = PromotionEvent(
        from_tier=current_tier,
        to_tier=target_tier,
        timestamp=datetime.now(timezone.utc),
        judge=judge,
        reason=f"Promoted from {current_tier.value} to {target_tier.value}",
    )

    return PromotionOutcome.Promoted(
        new_tier=target_tier,
        new_adjudication=new_adjudication,
        event=event,
    )


# ═══════════════════════════════════════════════════════════════════════════
#  External-source Candidate Registry
# ═══════════════════════════════════════════════════════════════════════════

# Known eligibility decisions (conservative — no candidate is marked eligible
# without independent licence review beyond DW1).
RegistryDecision = Literal[
    "candidate_only",
    "requires_licence_review",
]


class CapabilityLabel(BaseModel):
    """A single capability or linguistic-form label for a corpus candidate."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    label: str = Field(min_length=1)
    description: str | None = None


class RegistryEntry(BaseModel):
    """Metadata-only description of an external task-dialogue corpus candidate.

    This is a **strict metadata-only** record.  It must never contain dataset
    content, embedded dialogue payloads, licence acceptance, or eligibility
    claims.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    name: str = Field(min_length=1, description="Short human-readable name")
    official_url: str = Field(
        min_length=1, description="Primary verifiable source URL"
    )
    declared_licence: str = Field(
        min_length=1,
        description="Verbatim licence string as declared by the source",
    )
    licence_notes: str | None = Field(
        default=None,
        description=(
            "Disclaimer: repository/code licences may differ from dataset "
            "licences. No licence is accepted by this evaluation."
        ),
    )
    capability_labels: list[CapabilityLabel] = Field(
        default_factory=list,
        description="Linguistic-form and task-dialogue capability labels",
    )
    estimated_count: int | None = Field(
        default=None, ge=0, description="Estimated number of dialogues (if known)"
    )
    decision: RegistryDecision = Field(
        description="Conservative evaluation decision — never 'eligible'"
    )
    access_notes: str | None = Field(
        default=None,
        description="Access posture and any restrictions",
    )

    @model_validator(mode="after")
    def _validate_decision(self) -> "RegistryEntry":
        if self.decision not in ("candidate_only", "requires_licence_review"):
            raise ValueError(
                f"Decision must be conservative; got {self.decision!r}"
            )
        return self


class CandidateRegistry(BaseModel):
    """Schema for an external-source candidate registry.

    The registry is an allowlist-based descriptor only — no dataset content,
    no licence acceptance, no cost assessment.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: str = "lc2.candidate_registry.v1"
    entries: list[RegistryEntry] = Field(min_length=1)


# ═══════════════════════════════════════════════════════════════════════════
#  Public API
# ═══════════════════════════════════════════════════════════════════════════

__all__ = [
    "AdjudicationState",
    "CandidateRegistry",
    "CapabilityLabel",
    "CorpusCandidate",
    "GeneratorIdentity",
    "JudgeIdentity",
    "ProvenanceTier",
    "PromotionEvent",
    "PromotionOutcome",
    "PromotionResult",
    "QuarantineDetail",
    "QuarantineReason",
    "RegistryEntry",
    "ScenarioFamily",
    "promote_candidate",
    "RegistryDecision",
]
