"""LC2 Corpus Factory — provenance tiers, promotion, quarantine, registry, wrapper.

This module is a strict pure-Python/Pydantic domain layer for the LC2 corpus
factory. It defines the provenance model, promotion rules, quarantine logic,
candidate registry, and the CorpusCandidate wrapper that embeds an unchanged
ReceptionScenarioSpec.

No provider, route, database, HTTP, or external-service dependency is
imported.  The module validates shape and policy only — it does not
semantically certify any candidate.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ─── LC1 canonical import (read-only reference) ────────────────────────────
from app.services.bernie.scenario_spec import ReceptionScenarioSpec

# ═══════════════════════════════════════════════════════════════════════════
#  Core enumerations
# ═══════════════════════════════════════════════════════════════════════════


class ProvenanceTier(str, Enum):
    """Provenance tier for a corpus candidate.

    - **gold**: Human/Sol-authored or independently adjudicated reference.
      Never generated by a model.
    - **silver**: Model-generated from a Gold seed, awaiting independent
      adjudication.
    - **bronze**: Unstructured or externally-sourced material that requires
      semantic adjudication before promotion.
    """

    GOLD = "gold"
    SILVER = "silver"
    BRONZE = "bronze"


class AdjudicationState(str, Enum):
    """Adjudication state of a corpus candidate.

    Only Sol (the protected orchestrator/integrator) may change a candidate's
    adjudication from ``pending`` to ``adjudicated``.
    """

    ADJUDICATED = "adjudicated"
    PENDING = "pending"
    QUARANTINE = "quarantine"


class ScenarioFamily(str, Enum):
    """Known scenario families covering the canonical LC1 action/family surface.

    Families: booking_create, booking_move, booking_resize, booking_cancel,
    status_change, explain_schedule, clarify_temporal, and adversarial.
    """

    BOOKING_CREATE = "booking_create"
    BOOKING_MOVE = "booking_move"
    BOOKING_RESIZE = "booking_resize"
    BOOKING_CANCEL = "booking_cancel"
    STATUS_CHANGE = "status_change"
    EXPLAIN_SCHEDULE = "explain_schedule"
    CLARIFY_TEMPORAL = "clarify_temporal"
    ADVERSARIAL = "adversarial"


class QuarantineReason(str, Enum):
    """Machine-readable reasons for quarantining a candidate.

    Every quarantine outcome must carry exactly one of these reasons.
    ``generator_equals_judge`` has been removed as a duplicate of
    ``self_certification``.
    """

    SELF_CERTIFICATION = "self_certification"
    SCHEMA_INVALID = "schema_invalid"
    AUTHORITY_BREACH = "authority_breach"
    EVIDENCE_MISMATCH = "evidence_mismatch"
    MISSING_PROVENANCE = "missing_provenance"
    UNSAFE_INSTRUCTION = "unsafe_instruction"
    INVALID_TIER_TRANSITION = "invalid_tier_transition"
    MISSING_SOURCE_GOLD = "missing_source_gold"
    ADJUDICATION_REJECTED = "adjudication_rejected"
    ADJUDICATION_DISPUTED = "adjudication_disputed"
    DERIVATION_MISMATCH = "derivation_mismatch"
    GENERATOR_AUTHORITY_GRANT = "generator_authority_grant"


# ═══════════════════════════════════════════════════════════════════════════
#  Generator / Judge identity records
# ═══════════════════════════════════════════════════════════════════════════


class GeneratorIdentity(BaseModel):
    """Immutable identity record for a candidate generator.

    Identity comparison for the self-certification gate is by ``model_id``
    only — two instances of the same model are considered the same
    identity for independence purposes.  ``instance_id`` is preserved for
    traceability but does not affect the independence check.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    model_id: str = Field(min_length=1, description="Generator model identifier")
    instance_id: str | None = Field(
        default=None,
        description="Optional instance or lane identifier for traceability",
    )

    def stable_key(self) -> str:
        """Return a deterministic string key for identity comparison."""
        return f"{self.model_id}::{self.instance_id or ''}"

    def model_key(self) -> str:
        """Return model-level key (ignores instance) for self-certification gate."""
        return self.model_id


class JudgeIdentity(BaseModel):
    """Immutable identity record for an independent judge.

    Identity comparison for the self-certification gate is by ``model_id``
    only — two instances of the same model are considered the same
    identity for independence purposes.  ``instance_id`` is preserved for
    traceability.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    model_id: str = Field(min_length=1, description="Judge model identifier")
    instance_id: str | None = Field(
        default=None,
        description="Optional instance or lane identifier for traceability",
    )

    def stable_key(self) -> str:
        return f"{self.model_id}::{self.instance_id or ''}"

    def model_key(self) -> str:
        return self.model_id


# ═══════════════════════════════════════════════════════════════════════════
#  Authority-grant model (explicit structured policy)
# ═══════════════════════════════════════════════════════════════════════════


class AuthorityGrant(BaseModel):
    """Explicit, strict authority grant for a corpus candidate.

    For generated (Silver/Bronze) candidates all fields must remain
    ``False``.  Only Gold candidates authored by Sol may carry a non-empty
    grant.  ``forbidden_tool_calls`` in the embedded scenario is a
    *restriction* and is never treated as granted authority.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    provider_write: bool = False
    diary_write: bool = False
    confirmation: bool = False
    override_authority: bool = False


# ═══════════════════════════════════════════════════════════════════════════
#  Adjudication record (strict immutable evidence)
# ═══════════════════════════════════════════════════════════════════════════


class AdjudicationRecord(BaseModel):
    """Strict immutable record of an independent adjudication.

    This is the sole evidence of independent review.  A candidate may only
    be promoted when the record carries ``decision == "accepted"``.
    Rejected or disputed adjudications cause quarantine.

    The ``timestamp`` is supplied as evidence (deterministic) — it is never
    generated by ``datetime.now()`` inside this module.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    decision: Literal["accepted", "rejected", "disputed"]
    judge: JudgeIdentity
    timestamp: datetime = Field(description="Deterministic timestamp supplied as evidence")
    checked_semantic_scope: str = Field(
        min_length=1,
        description="What semantic scope was checked (e.g. action, entity, temporal)",
    )
    checked_evidence_scope: str = Field(
        min_length=1,
        description="What evidence was checked (e.g. source_spans, dialogue_turns)",
    )
    evidence_ref: str = Field(
        min_length=1,
        description="Reference to supporting evidence (e.g. evidence document ID)",
    )


# ═══════════════════════════════════════════════════════════════════════════
#  Promotion-history record
# ═══════════════════════════════════════════════════════════════════════════


class PromotionEvent(BaseModel):
    """One recorded promotion step in a candidate's history."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    from_tier: ProvenanceTier
    to_tier: ProvenanceTier
    timestamp: datetime
    judge: JudgeIdentity | None = None
    reason: str | None = None


# ═══════════════════════════════════════════════════════════════════════════
#  Quarantine detail (carried inside PromotionResult for rejected cases)
# ═══════════════════════════════════════════════════════════════════════════


class QuarantineDetail(BaseModel):
    """Detail record attached to a quarantine promotion result."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    reason: QuarantineReason
    message: str = Field(min_length=1)
    details: dict[str, Any] | None = None


# ═══════════════════════════════════════════════════════════════════════════
#  Promotion result (discriminated union via tagged union pattern)
# ═══════════════════════════════════════════════════════════════════════════


class PromotionOutcome:
    """Namespace for promotion-result types so callers can pattern-match.

    Usage::

        result = promote_candidate(candidate, adjudication)
        if isinstance(result, PromotionOutcome.Promoted):
            ...
        elif isinstance(result, PromotionOutcome.Quarantined):
            ...
        elif isinstance(result, PromotionOutcome.Rejected):
            ...
    """

    class Promoted(BaseModel):
        """The candidate was successfully promoted.

        Returns the resulting **immutable** candidate with updated
        provenance/adjudication, judge/adjudication evidence, and appended
        promotion history.  Callers receive the changed candidate directly,
        not detached metadata.
        """

        model_config = ConfigDict(extra="forbid", frozen=True)

        outcome: Literal["promoted"] = "promoted"
        candidate: "CorpusCandidate"

    class Quarantined(BaseModel):
        """The candidate was placed in quarantine with a reason."""

        model_config = ConfigDict(extra="forbid", frozen=True)

        outcome: Literal["quarantined"] = "quarantined"
        quarantine: QuarantineDetail

    class Rejected(BaseModel):
        """The candidate was rejected (not eligible for the requested promotion)."""

        model_config = ConfigDict(extra="forbid", frozen=True)

        outcome: Literal["rejected"] = "rejected"
        reason: str = Field(min_length=1)


PromotionResult = (
    PromotionOutcome.Promoted
    | PromotionOutcome.Quarantined
    | PromotionOutcome.Rejected
)


# ═══════════════════════════════════════════════════════════════════════════
#  CorpusCandidate wrapper
# ═══════════════════════════════════════════════════════════════════════════


def _compute_derivation_id(
    source_scenario_id: str,
    generator_model_id: str,
    *,
    seed: str = "",
) -> str:
    """Deterministic full ``sha256:<64hex>`` derivation ID.

    Reproducible from **source-scenario content** (identified by its ID) plus
    explicit transformation parameters (``seed``) and generator **model**
    identity.  Timestamp and lane instance must **not** change the derivation.
    """
    raw = f"{source_scenario_id}::{generator_model_id}::{seed}"
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def _validate_derivation_id(
    source_scenario_id: str,
    generator_model_id: str,
    seed: str,
    supplied: str | None,
) -> str | None:
    """Validate and optionally return a recomputed derivation ID.

    If ``supplied`` is ``None`` the caller must generate one externally.
    If supplied it is recomputed and a mismatch is signalled via ``ValueError``.
    Returns the canonical derivation ID for storage.
    """
    if supplied is None:
        return None
    # Validate format first (before content check)
    if not supplied.startswith("sha256:") or len(supplied) != 71:
        raise ValueError(
            f"derivation_id must be 'sha256:<64 hex>' format, got {supplied!r}"
        )
    hex_part = supplied[7:]
    if not all(c in "0123456789abcdef" for c in hex_part):
        raise ValueError(
            f"derivation_id hex part must be lowercase hex, got {hex_part!r}"
        )
    # Then recompute and check content
    expected = _compute_derivation_id(
        source_scenario_id, generator_model_id, seed=seed
    )
    if supplied != expected:
        raise ValueError(
            f"Supplied derivation_id {supplied!r} does not match "
            f"recomputed value {expected!r}"
        )
    return supplied


def _check_authority_grant(grant: AuthorityGrant) -> QuarantineDetail | None:
    """Return a quarantine detail if a non-empty authority grant is found."""
    if grant.provider_write or grant.diary_write or grant.confirmation or grant.override_authority:
        true_fields = [
            k for k, v in grant.model_dump().items() if v
        ]
        return QuarantineDetail(
            reason=QuarantineReason.GENERATOR_AUTHORITY_GRANT,
            message=f"Generated candidate must have empty authority grant, got: {true_fields}",
            details={"granted_fields": true_fields},
        )
    return None


class CorpusCandidate(BaseModel):
    """Strict evidence wrapper around a ``ReceptionScenarioSpec``.

    This type is the unit of transport between workers.  The embedded scenario
    spec is never mutated by the wrapper; all provenance metadata lives in
    wrapper fields.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    # ── Mandatory provenance fields ───────────────────────────────────────
    provenance: ProvenanceTier
    adjudication: AdjudicationState
    family: ScenarioFamily

    generator_identity: GeneratorIdentity | None = None
    judge_identity: JudgeIdentity | None = None
    generation_timestamp: datetime | None = None

    # Source Gold scenario ID (required for Silver; optional for Bronze;
    # must be absent for Gold)
    source_scenario_id: str | None = Field(
        default=None, min_length=1, description="Source Gold scenario_id"
    )

    # Stable derivation identifier — full sha256:<64hex>
    derivation_id: str | None = Field(
        default=None,
        description="Full sha256:<64hex> derivation hash (reproducible from source + params + model)",
    )
    derivation_seed: str = Field(
        default="", description="Seed string fed into derivation hash"
    )

    # Explicit authority grant (must be empty for generated candidates)
    authority_grant: AuthorityGrant = Field(default_factory=AuthorityGrant)

    # Adjudication record (evidence of independent review)
    adjudication_record: AdjudicationRecord | None = None

    # Promotion history (oldest first)
    promotion_history: list[PromotionEvent] = Field(default_factory=list)

    # ── Embedded LC1 scenario (never mutated by this wrapper) ─────────────
    scenario: ReceptionScenarioSpec

    # ── Validators ────────────────────────────────────────────────────────

    @field_validator("generation_timestamp", mode="before")
    @classmethod
    def _coerce_timestamp(cls, value: object) -> object:
        if isinstance(value, str):
            return datetime.fromisoformat(value)
        return value

    @field_validator("derivation_id", mode="before")
    @classmethod
    def _validate_derivation_format(cls, value: object) -> object:
        """Validate derivation_id format if supplied."""
        if value is None or not isinstance(value, str):
            return value
        if not value.startswith("sha256:") or len(value) != 71:
            raise ValueError(
                f"derivation_id must be 'sha256:<64 hex>' format, got {value!r}"
            )
        hex_part = value[7:]
        if not all(c in "0123456789abcdef" for c in hex_part):
            raise ValueError(
                f"derivation_id hex part must be lowercase hex, got {hex_part!r}"
            )
        return value

    @model_validator(mode="after")
    def _validate_provenance_consistency(self) -> "CorpusCandidate":
        """Fail-closed checks for provenance consistency."""
        if self.provenance == ProvenanceTier.GOLD:
            if self.generator_identity is not None:
                raise ValueError("Gold candidates must not carry a generator_identity")
            if self.adjudication != AdjudicationState.ADJUDICATED:
                raise ValueError("Gold candidates must be adjudicated")
            if self.source_scenario_id is not None:
                raise ValueError("Gold candidates must not carry a source_scenario_id")
        elif self.provenance == ProvenanceTier.SILVER:
            if self.generator_identity is None:
                raise ValueError("Silver candidates must carry a generator_identity")
            if self.generation_timestamp is None:
                raise ValueError("Silver candidates must carry a generation_timestamp")
            if self.source_scenario_id is None:
                raise ValueError("Silver candidates must carry a source_scenario_id")
        elif self.provenance == ProvenanceTier.BRONZE:
            # Bronze candidates (external/discovery) may or may not have a source
            if self.generator_identity is None:
                raise ValueError("Bronze candidates must carry a generator_identity")
            if self.generation_timestamp is None:
                raise ValueError("Bronze candidates must carry a generation_timestamp")
            # source_scenario_id is OPTIONAL for Bronze

        return self

    @model_validator(mode="after")
    def _validate_metadata_agreement(self) -> "CorpusCandidate":
        """Fail-closed: wrapper and embedded scenario metadata must agree.

        A Silver/pending wrapper around a Gold/adjudicated scenario is
        rejected.  The wrapper owns the definitive metadata; the scenario
        must match.
        """
        scenario = self.scenario
        if scenario.provenance != self.provenance.value:
            raise ValueError(
                f"Wrapper provenance {self.provenance.value!r} does not match "
                f"embedded scenario provenance {scenario.provenance!r}"
            )
        if scenario.adjudication != self.adjudication.value:
            raise ValueError(
                f"Wrapper adjudication {self.adjudication.value!r} does not match "
                f"embedded scenario adjudication {scenario.adjudication!r}"
            )
        if scenario.family != self.family.value:
            raise ValueError(
                f"Wrapper family {self.family.value!r} does not match "
                f"embedded scenario family {scenario.family!r}"
            )
        return self

    @model_validator(mode="after")
    def _validate_authority_grant(self) -> "CorpusCandidate":
        """Generated candidates must have an empty authority grant."""
        if self.provenance in (ProvenanceTier.SILVER, ProvenanceTier.BRONZE):
            grant = self.authority_grant
            if grant.provider_write or grant.diary_write or grant.confirmation or grant.override_authority:
                true_fields = [
                    k for k, v in grant.model_dump().items() if v
                ]
                raise ValueError(
                    f"Generated candidate must have empty authority grant, "
                    f"got: {true_fields}"
                )
        return self

    def stable_key(self) -> str:
        """Return a deterministic key for identity/equality comparison."""
        return f"{self.provenance.value}::{self.scenario.scenario_id}::{self.derivation_id or ''}"


# ═══════════════════════════════════════════════════════════════════════════
#  Promotion engine
# ═══════════════════════════════════════════════════════════════════════════


def _check_self_certification(
    candidate: CorpusCandidate, adjudication: AdjudicationRecord | None
) -> QuarantineDetail | None:
    """Return a quarantine detail if the candidate is self-certified.

    Independence is at the **model** level, not instance level.  Two
    instances/lanes of the same provider model cannot certify that model's
    generated candidate.  ``model_key()`` is used for comparison;
    ``instance_id`` is preserved for traceability only.
    """
    if candidate.generator_identity is None:
        return None
    if adjudication is None:
        return None
    gen_key = candidate.generator_identity.model_key()
    judge_key = adjudication.judge.model_key()
    if gen_key == judge_key:
        return QuarantineDetail(
            reason=QuarantineReason.SELF_CERTIFICATION,
            message=(
                "Generator and judge must differ at the model level; "
                f"both have model_id={gen_key!r}"
            ),
            details={
                "generator_model_id": candidate.generator_identity.model_id,
                "generator_instance_id": candidate.generator_identity.instance_id,
                "judge_model_id": adjudication.judge.model_id,
                "judge_instance_id": adjudication.judge.instance_id,
            },
        )
    return None


def _check_schema_validity(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if the embedded scenario fails validation."""
    try:
        _ = ReceptionScenarioSpec.model_validate(
            candidate.scenario.model_dump()
        )
    except Exception as exc:
        return QuarantineDetail(
            reason=QuarantineReason.SCHEMA_INVALID,
            message=f"Embedded scenario validation failed: {exc}",
        )
    return None


def _check_evidence_mismatch(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if source spans don't match utterance text."""
    scenario = candidate.scenario
    utterances = [
        turn.get("utterance", "")
        for turn in scenario.dialogue_turns
        if isinstance(turn, dict) and "utterance" in turn
    ]
    for field_name, spans in scenario.source_spans.items():
        for span in spans:
            if isinstance(span, dict):
                turn_index = span.get("turn_index", 0)
                start = span.get("start", 0)
                end = span.get("end", 0)
                text = span.get("text", "")
            else:
                turn_index = span.turn_index
                start = span.start
                end = span.end
                text = span.text
            if turn_index >= len(utterances):
                return QuarantineDetail(
                    reason=QuarantineReason.EVIDENCE_MISMATCH,
                    message=f"source_spans[{field_name!r}] references missing turn {turn_index}",
                    details={
                        "field": field_name,
                        "turn_index": turn_index,
                        "available_turns": len(utterances),
                    },
                )
            original = utterances[turn_index]
            if end > len(original) or original[start:end] != text:
                return QuarantineDetail(
                    reason=QuarantineReason.EVIDENCE_MISMATCH,
                    message=(
                        f"source_spans[{field_name!r}] text mismatch at "
                        f"turn {turn_index}[{start}:{end}]: "
                        f"expected {original[start:end]!r}, got {text!r}"
                    ),
                    details={
                        "field": field_name,
                        "turn_index": turn_index,
                        "start": start,
                        "end": end,
                        "expected": original[start:end],
                        "got": text,
                    },
                )
    return None


def _check_missing_provenance(
    candidate: CorpusCandidate,
) -> QuarantineDetail | None:
    """Return a quarantine detail if required provenance fields are missing."""
    if candidate.provenance == ProvenanceTier.SILVER:
        missing = []
        if candidate.generator_identity is None:
            missing.append("generator_identity")
        if candidate.generation_timestamp is None:
            missing.append("generation_timestamp")
        if candidate.source_scenario_id is None:
            missing.append("source_scenario_id")
        if missing:
            return QuarantineDetail(
                reason=QuarantineReason.MISSING_PROVENANCE,
                message=f"Missing required provenance fields: {', '.join(missing)}",
                details={"missing_fields": missing, "tier": "silver"},
            )
    elif candidate.provenance == ProvenanceTier.BRONZE:
        missing = []
        if candidate.generator_identity is None:
            missing.append("generator_identity")
        if candidate.generation_timestamp is None:
            missing.append("generation_timestamp")
        if missing:
            return QuarantineDetail(
                reason=QuarantineReason.MISSING_PROVENANCE,
                message=f"Missing required provenance fields: {', '.join(missing)}",
                details={"missing_fields": missing, "tier": "bronze"},
            )
    return None


def promote_candidate(
    candidate: CorpusCandidate,
    adjudication: AdjudicationRecord | None = None,
    *,
    target_tier: ProvenanceTier | None = None,
) -> PromotionResult:
    """Attempt to promote a candidate to the next tier.

    This function is the sole deterministic promotion gate.  It checks:

    * Self-certification (generator model_id == judge model_id)
    * Schema validity of the embedded scenario
    * Source-span evidence match
    * Missing provenance fields
    * Valid tier transitions
    * Authority grant (must be empty for generated candidates)
    * Adjudication record decision (must be ``"accepted"``)
    * Derivation ID format and consistency

    Parameters
    ----------
    candidate :
        The corpus candidate to promote.
    adjudication :
        The independent adjudication record.  Must have
        ``decision == "accepted"`` for any promotion.  Bare
        ``JudgeIdentity`` is never sufficient.
    target_tier :
        Explicit target tier.  If omitted, the default transition path is
        used (Bronze -> Silver, Silver -> Gold).

    Returns
    -------
    PromotionResult
        ``Promoted`` (with the updated immutable candidate) if the
        promotion succeeds, ``Quarantined`` or ``Rejected`` otherwise.
    """
    # ── Belt-and-suspenders: re-check Pydantic validity ──────────────────
    try:
        _ = candidate.model_dump()
    except Exception as exc:
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.SCHEMA_INVALID,
                message=f"Candidate model validation failed: {exc}",
            )
        )

    # ── Run all quarantine checks ─────────────────────────────────────────
    checks = [
        ("self-certification", _check_self_certification(candidate, adjudication)),
        ("schema validity", _check_schema_validity(candidate)),
        ("evidence match", _check_evidence_mismatch(candidate)),
        ("missing provenance", _check_missing_provenance(candidate)),
        ("authority grant", _check_authority_grant(candidate.authority_grant)),
    ]

    for check_name, detail in checks:
        if detail is not None:
            return PromotionOutcome.Quarantined(quarantine=detail)

    # ── Adjudication record gate ──────────────────────────────────────────
    # Bronze -> Silver and Silver -> Gold require an accepted independent
    # record.  Rejected/disputed adjudications quarantine.
    if adjudication is None:
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.MISSING_PROVENANCE,
                message="Promotion requires an adjudication record",
            )
        )

    if adjudication.decision == "rejected":
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.ADJUDICATION_REJECTED,
                message="Adjudication record decision is 'rejected'",
                details={
                    "judge_model_id": adjudication.judge.model_id,
                    "evidence_ref": adjudication.evidence_ref,
                },
            )
        )

    if adjudication.decision == "disputed":
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.ADJUDICATION_DISPUTED,
                message="Adjudication record decision is 'disputed'",
                details={
                    "judge_model_id": adjudication.judge.model_id,
                    "evidence_ref": adjudication.evidence_ref,
                },
            )
        )

    # ── Derivation ID verification ────────────────────────────────────────
    if candidate.derivation_id is not None:
        gen_model_id = (
            candidate.generator_identity.model_id
            if candidate.generator_identity
            else "unknown"
        )
        src_id = candidate.source_scenario_id or "unknown"
        try:
            _validate_derivation_id(
                src_id,
                gen_model_id,
                candidate.derivation_seed,
                candidate.derivation_id,
            )
        except ValueError as exc:
            return PromotionOutcome.Quarantined(
                quarantine=QuarantineDetail(
                    reason=QuarantineReason.DERIVATION_MISMATCH,
                    message=str(exc),
                    details={
                        "supplied": candidate.derivation_id,
                        "source_scenario_id": src_id,
                        "generator_model_id": gen_model_id,
                        "seed": candidate.derivation_seed,
                    },
                )
            )

    # ── Determine target tier ─────────────────────────────────────────────
    current_tier = candidate.provenance

    if target_tier is None:
        if current_tier == ProvenanceTier.BRONZE:
            target_tier = ProvenanceTier.SILVER
        elif current_tier == ProvenanceTier.SILVER:
            target_tier = ProvenanceTier.GOLD
        elif current_tier == ProvenanceTier.GOLD:
            return PromotionOutcome.Rejected(
                reason="Gold candidates cannot be promoted further"
            )
        else:
            return PromotionOutcome.Rejected(
                reason=f"Unknown provenance tier: {current_tier}"
            )

    # ── Validate transition legality ──────────────────────────────────────
    valid_transitions = {
        ProvenanceTier.BRONZE: {ProvenanceTier.SILVER},
        ProvenanceTier.SILVER: {ProvenanceTier.GOLD},
        ProvenanceTier.GOLD: set(),
    }

    allowed = valid_transitions.get(current_tier, set())
    if target_tier not in allowed:
        return PromotionOutcome.Quarantined(
            quarantine=QuarantineDetail(
                reason=QuarantineReason.INVALID_TIER_TRANSITION,
                message=(
                    f"Invalid transition: {current_tier.value} -> "
                    f"{target_tier.value}"
                ),
                details={
                    "from": current_tier.value,
                    "to": target_tier.value,
                    "allowed": [t.value for t in allowed],
                },
            )
        )

    # ── Promotion-specific checks ─────────────────────────────────────────
    if target_tier == ProvenanceTier.GOLD:
        if current_tier != ProvenanceTier.SILVER:
            return PromotionOutcome.Quarantined(
                quarantine=QuarantineDetail(
                    reason=QuarantineReason.INVALID_TIER_TRANSITION,
                    message="Only Silver candidates may be promoted to Gold",
                )
            )

    # ── Compute new candidate state ───────────────────────────────────────
    new_adjudication = (
        AdjudicationState.ADJUDICATED
        if target_tier == ProvenanceTier.GOLD
        else AdjudicationState.PENDING
    )

    # Timestamp comes from the adjudication record, never datetime.now()
    promotion_timestamp = adjudication.timestamp

    event = PromotionEvent(
        from_tier=current_tier,
        to_tier=target_tier,
        timestamp=promotion_timestamp,
        judge=adjudication.judge,
        reason=f"Promoted from {current_tier.value} to {target_tier.value}",
    )

    # Build the updated immutable candidate.
    # The embedded scenario's metadata fields are updated to match the new
    # wrapper state so the metadata-agreement validator passes.
    new_history = list(candidate.promotion_history) + [event]

    updated_scenario = ReceptionScenarioSpec.model_validate(
        {
            **candidate.scenario.model_dump(),
            "provenance": target_tier.value,
            "adjudication": new_adjudication.value,
        }
    )

    # Gold candidates must not carry generator_identity or source_scenario_id
    updated_generator = (
        None if target_tier == ProvenanceTier.GOLD
        else candidate.generator_identity
    )
    updated_source_id = (
        None if target_tier == ProvenanceTier.GOLD
        else candidate.source_scenario_id
    )

    updated = CorpusCandidate(
        provenance=target_tier,
        adjudication=new_adjudication,
        family=candidate.family,
        generator_identity=updated_generator,
        judge_identity=adjudication.judge,
        generation_timestamp=candidate.generation_timestamp,
        source_scenario_id=updated_source_id,
        derivation_id=candidate.derivation_id,
        derivation_seed=candidate.derivation_seed,
        authority_grant=candidate.authority_grant,
        adjudication_record=adjudication,
        promotion_history=new_history,
        scenario=updated_scenario,
    )

    return PromotionOutcome.Promoted(candidate=updated)


# ═══════════════════════════════════════════════════════════════════════════
#  External-source Candidate Registry
# ═══════════════════════════════════════════════════════════════════════════

# Known eligibility decisions (conservative — no candidate is marked eligible
# without independent licence review beyond DW1).
RegistryDecision = Literal[
    "candidate_only",
    "requires_licence_review",
]


class CapabilityLabel(BaseModel):
    """A single capability or linguistic-form label for a corpus candidate."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    label: str = Field(min_length=1)
    description: str | None = None


class RegistryEntry(BaseModel):
    """Metadata-only description of an external task-dialogue corpus candidate.

    This is a **strict metadata-only** record.  It must never contain dataset
    content, embedded dialogue payloads, licence acceptance, or eligibility
    claims.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    name: str = Field(min_length=1, description="Short human-readable name")
    official_url: str = Field(
        min_length=1, description="Primary verifiable source URL"
    )
    declared_licence: str = Field(
        min_length=1,
        description="Verbatim licence string as declared by the source",
    )
    licence_notes: str | None = Field(
        default=None,
        description=(
            "Disclaimer: repository/code licences may differ from dataset "
            "licences. No licence is accepted by this evaluation."
        ),
    )
    capability_labels: list[CapabilityLabel] = Field(
        default_factory=list,
        description="Linguistic-form and task-dialogue capability labels",
    )
    estimated_count: int | None = Field(
        default=None, ge=0, description="Estimated number of dialogues (if known)"
    )
    decision: RegistryDecision = Field(
        description="Conservative evaluation decision — never 'eligible'"
    )
    access_notes: str | None = Field(
        default=None,
        description="Access posture and any restrictions",
    )

    @model_validator(mode="after")
    def _validate_decision(self) -> "RegistryEntry":
        if self.decision not in ("candidate_only", "requires_licence_review"):
            raise ValueError(
                f"Decision must be conservative; got {self.decision!r}"
            )
        return self

    @model_validator(mode="after")
    def _validate_healthcare_entry(self) -> "RegistryEntry":
        """Specific gate for Healthcare Appointment Booking Calls Dataset."""
        if "healthcare" in self.name.lower() and "appointment" in self.name.lower():
            if self.decision != "requires_licence_review":
                raise ValueError(
                    "Healthcare Appointment dataset must be marked "
                    "requires_licence_review"
                )
        return self


class CandidateRegistry(BaseModel):
    """Schema for an external-source candidate registry.

    The registry is an allowlist-based descriptor only — no dataset content,
    no licence acceptance, no cost assessment.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: str = "lc2.candidate_registry.v1"
    entries: list[RegistryEntry] = Field(min_length=1)


# ═══════════════════════════════════════════════════════════════════════════
#  Public API
# ═══════════════════════════════════════════════════════════════════════════

__all__ = [
    "AdjudicationRecord",
    "AdjudicationState",
    "AuthorityGrant",
    "CandidateRegistry",
    "CapabilityLabel",
    "CorpusCandidate",
    "GeneratorIdentity",
    "JudgeIdentity",
    "ProvenanceTier",
    "PromotionEvent",
    "PromotionOutcome",
    "PromotionResult",
    "QuarantineDetail",
    "QuarantineReason",
    "RegistryEntry",
    "ScenarioFamily",
    "promote_candidate",
    "RegistryDecision",
    "_compute_derivation_id",
    "_validate_derivation_id",
]
